# Generated by Django 4.2.10 on 2024-02-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_image_description_alter_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(help_text='Enter the image title.', max_length=128, verbose_name='Image title'),
        ),
    ]
