# Generated by Django 4.2.10 on 2024-02-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(help_text='Max 128 characters. Required.', max_length=128, verbose_name='Image title'),
        ),
    ]
